// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceAnalytics.DAL;

#nullable disable

namespace PriceAnalytics.DAL.Migrations
{
    [DbContext(typeof(PriceAnalyticsDbContext))]
    [Migration("20250523085154_UpdateDailyResultModel")]
    partial class UpdateDailyResultModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.Comment", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.Customer", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.DailyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AcceptedVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OfferedVolume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("DailyResults");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.HourData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowDataId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RowDataId");

                    b.ToTable("HourData");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.RowData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleApplicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleApplicationId");

                    b.ToTable("RowData");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.SaleApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaleApplications");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.Comment", b =>
                {
                    b.HasOne("PriceAnalytics.Core.DbModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.DailyResult", b =>
                {
                    b.HasOne("PriceAnalytics.Core.DbModels.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.HourData", b =>
                {
                    b.HasOne("PriceAnalytics.Core.DbModels.RowData", "Row")
                        .WithMany("Hours")
                        .HasForeignKey("RowDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.RowData", b =>
                {
                    b.HasOne("PriceAnalytics.Core.DbModels.SaleApplication", "SaleApplication")
                        .WithMany("Rows")
                        .HasForeignKey("SaleApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleApplication");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.RowData", b =>
                {
                    b.Navigation("Hours");
                });

            modelBuilder.Entity("PriceAnalytics.Core.DbModels.SaleApplication", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
